- hosts: main
  sudo: yes
  tasks:

    - apt: update_cache=yes
    - name: install libs
      apt: name={{item}} state=installed
      with_items:
        - git

        - gcc
        - g++
        - llvm-3.6-dev
        - libedit-dev

        - python-pip
        - python-dev
        - python-matplotlib
        - python-pil
        - python-numpy
        - python-sympy
        - python-pandas
        - python-scipy
        - python-sklearn
        - cython

    - shell: hostname {{hostname}}
    - template: src=templates/hosts dest=/etc/hosts
    - template: src=templates/hostname dest=/etc/hostname

    - shell: echo "cd ~/data/" > .bash_profile
      sudo: no

    - shell: pip install --upgrade pip

    - pip: name={{item}}
      environment:
        LLVM_CONFIG: '/usr/bin/llvm-config-3.6'
      with_items:
        - jupyter
        - enum34
        - llvmlite==0.8.0
        - numba==0.23.1
